In [2]:
import numpy as np

In [31]:
A = np.random.randn(1, 11, 12)
print(A)

[[[-3.85658969e-01 -5.45976397e-01  1.20055048e+00 -1.84516331e-01
   -1.41680967e-01  3.94158013e-01  1.00650035e+00  3.50295879e-01
   -1.15208750e+00 -1.41363619e+00 -9.67088667e-01  1.56770293e-01
   -1.00389720e+00  1.00134580e+00  2.95009965e-01 -5.77372423e-01
   -1.70667640e+00  3.32982223e-01  2.01580724e+00 -6.87502490e-01
   -9.62995406e-01  1.23567733e+00  3.81577543e-01  7.15968548e-01
    3.78292902e-01 -2.74002097e-01 -1.62967520e+00 -8.44703974e-01
   -8.60994223e-02  4.38977405e-01 -1.10061336e-01  2.80797610e+00
   -9.97322671e-01  1.56641845e+00  1.92192617e+00 -1.72838244e-01
   -1.45278663e+00 -7.49782790e-01 -1.65744214e-01  2.23535613e-02
   -5.09152785e-01  2.45876893e+00 -8.80951227e-01  4.75284386e-01
    1.47306478e+00  8.67667744e-02 -5.07062659e-01  1.68937473e-01
    4.69140397e-01  8.25043344e-01  2.59183535e-01 -7.06474881e-01
    7.94577054e-01  8.17620063e-02  2.10732908e-01 -1.25298253e+00
    1.16422028e+00 -9.41770674e-02  1.12104373e+00 -1.02001613

In [32]:
s = 5
b, c, w = A.shape
w_out = (w * s) - (s - 1)
Z = np.zeros((b, c, w_out), dtype=A.dtype)  # TODO
Z[:, :, :: s] = A
print(Z.shape)

(1, 11, 296)


In [26]:
s = 3
b, c, w, h = A.shape
w_out = (w * s) - (s - 1)
h_out = (h * s) - (s - 1)
Z = np.zeros((b, c, w_out, h_out), dtype=A.dtype)  # TODO
Z[:, :, :: s, :: s] = A
print(Z)

ValueError: not enough values to unpack (expected 4, got 3)

In [9]:
z = a[:, ::2, :: 2]
print(z)

[[[ 0  2  4]
  [10 12 14]]

 [[20 22 24]
  [30 32 34]]]
